import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import './globals.css'
import Link from 'next/link';
import { Navbar } from './components/nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const cx = (...classes: any[]) => classes.filter(Boolean).join(' ');

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      className={cx('text-black bg-white dark:text-white dark:bg-[#111010]',
      GeistSans.variable,
      GeistMono.variable
  )}
    >
      <body className="max-w-xl flex flex-col mx-auto">
        <main className='flex-auto flex flex-col mt-6'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
