import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "./components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = {
  "/about": {
    name: "About",
  },
  "/projects": {
    name: "Projects",
  },
  "/blog": {
    name: "Blog",
  },
};

const cx = (...classes: any[]) => classes.filter(Boolean).join(" ");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cx("", GeistSans.variable, GeistMono.variable)}>
      <head />
      <body className="min-h-screen dark:bg-[#1b1b1f] dark:text-white font-sans antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex min-h-screen flex-col">
            <header className="container z-40">
              <div className="flex h-20 items-center justify-between py-6">
                <div>
                  <h1 className="text-xl font-bold tracking-tighter">
                    Justin Solo
                  </h1>
                </div>
                <nav className="hidden md:flex gap-3">
                  {Object.entries(navLinks).map(([path, { name }]) => (
                    <Link
                      href={path}
                      key={path}
                      className="flex items-center text-lg font-medium transition-all sm:text-sm text-neutral-700 dark:text-neutral-200"
                    >
                      {name}
                    </Link>
                  ))}
                </nav>
              </div>
            </header>
            <main className="flex-1">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
